### ISSUE TITLE
Grid

### ISSUE THREAD

**Issue by roybarber** [wearedamage/principletemplates#13]
Can you change to 12 Col Grid and do the following on the Cards

class="col-xs-12 col-sm-6 col-md-4 col-lg-3"

You may also need to adjust other page templates to be 12 col

**Comment by holliepearson** [comment]
Are you sure you want me to change this? The designs use an 8 column grid, using 12 won't match them exactly.

**Comment by roybarber** [comment]
positive and it will be easy!
