### ISSUE TITLE
Content for Advertise Page

### ISSUE THREAD

**Issue by holliepearson** [wearedamage/principletemplates#3]
This page is currently blank.

**Comment by roybarber** [comment]
Page Content:

Principle templates is the number one top ranked resource for downloading templates to learn from or to add to projects for Principle (LINK).

We offer many types of advertising partnerships, including bespoke campaigns and packages. If you have an idea you think we could help with, then please get in touch.

**Display Adverts**
We have many display advert positions available across the site, we can arrange an impression, click or time based campaign.

**Takeover Adverts**
We can do full website takeover adverts from homepage only, category pages or full site.

Newsletter Advertising & Sponsorship
With a huge newsletter following, we have the opportunity to sponsor or advertise directly on our weekly newsletters.

To speak to a member of the team about advertising send us a quick email to help@principletemplates.com (LINK)
