### ISSUE TITLE
Advert

### ISSUE THREAD

**Issue by roybarber** [wearedamage/principletemplates#6]
Can you add this advert into each loop of cards.
![screen shot 2017-01-03 at 15 38 10](https://cloud.githubusercontent.com/assets/2923782/21612877/bf6eedb4-d1ca-11e6-9dd4-ea042b79cc37.png)

The image and title should be editable inside wordpress

**Comment by roybarber** [comment]
Title: Download Amazing Sketch resources

**Comment by holliepearson** [comment]
Where does this need to link to?

**Comment by roybarber** [comment]
to https://thisisademo.com
